#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_SNOWGEM_VERSION=${VERSION_STRING[2]}
ELECTRUM_SNOWGEM_VERSION=${ELECTRUM_SNOWGEM_VERSION#\'}
ELECTRUM_SNOWGEM_VERSION=${ELECTRUM_SNOWGEM_VERSION%\'}
DOTS=`echo $ELECTRUM_SNOWGEM_VERSION |  grep -o "\." | wc -l`
if [[ $DOTS -lt 3 ]]; then
    ELECTRUM_ZCASH_APK_VERSION=$ELECTRUM_SNOWGEM_VERSION.0
else
    ELECTRUM_ZCASH_APK_VERSION=$ELECTRUM_SNOWGEM_VERSION
fi
export ELECTRUM_SNOWGEM_VERSION
export ELECTRUM_ZCASH_APK_VERSION
